#!/usr/bin/env bash
#
# DFOS Relay Topology Test
#
# Usage:
#   ./topology.sh [ring|mesh|star] [count]   Generate compose + start + smoke test
#   ./topology.sh smoke                      Run smoke test against running topology
#   ./topology.sh down                       Tear down
#
# Examples:
#   ./topology.sh ring 3     # 3 nodes in a ring (default)
#   ./topology.sh mesh 4     # 4 fully connected nodes
#   ./topology.sh star 5     # 1 hub + 4 spokes

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
COMPOSE_FILE="$SCRIPT_DIR/docker-compose.generated.yml"
BASE_PORT=9801
SYNC_INTERVAL="5s"

# ---------------------------------------------------------------------------
# topology generators
# ---------------------------------------------------------------------------

generate_ring() {
  local count=$1
  local services=""
  local volumes=""

  for i in $(seq 1 "$count"); do
    local name="relay-$(printf '%02d' "$i")"
    local next_i=$(( (i % count) + 1 ))
    local next_name="relay-$(printf '%02d' "$next_i")"
    local host_port=$((BASE_PORT + i - 1))

    services+="
  $name:
    build:
      context: ../..
      dockerfile: packages/dfos-web-relay-go/Dockerfile
    environment:
      PORT: \"8080\"
      RELAY_NAME: \"$name\"
      PEERS: \"http://$next_name:8080\"
      SYNC_INTERVAL: \"$SYNC_INTERVAL\"
    ports:
      - \"$host_port:8080\"
    volumes:
      - data-$name:/data
"
    volumes+="  data-$name:
"
  done

  cat > "$COMPOSE_FILE" <<EOF
# Generated by topology.sh — ring topology with $count nodes
services:
$services
volumes:
$volumes
EOF
}

generate_mesh() {
  local count=$1
  local services=""
  local volumes=""

  for i in $(seq 1 "$count"); do
    local name="relay-$(printf '%02d' "$i")"
    local host_port=$((BASE_PORT + i - 1))

    # peer with all other nodes
    local peers=""
    for j in $(seq 1 "$count"); do
      if [ "$j" -ne "$i" ]; then
        local peer_name="relay-$(printf '%02d' "$j")"
        if [ -n "$peers" ]; then peers+=","; fi
        peers+="http://$peer_name:8080"
      fi
    done

    services+="
  $name:
    build:
      context: ../..
      dockerfile: packages/dfos-web-relay-go/Dockerfile
    environment:
      PORT: \"8080\"
      RELAY_NAME: \"$name\"
      PEERS: \"$peers\"
      SYNC_INTERVAL: \"$SYNC_INTERVAL\"
    ports:
      - \"$host_port:8080\"
    volumes:
      - data-$name:/data
"
    volumes+="  data-$name:
"
  done

  cat > "$COMPOSE_FILE" <<EOF
# Generated by topology.sh — mesh topology with $count nodes
services:
$services
volumes:
$volumes
EOF
}

generate_star() {
  local count=$1
  local services=""
  local volumes=""
  local hub_name="relay-01"

  # hub peers with all spokes
  local hub_peers=""
  for i in $(seq 2 "$count"); do
    local spoke_name="relay-$(printf '%02d' "$i")"
    if [ -n "$hub_peers" ]; then hub_peers+=","; fi
    hub_peers+="http://$spoke_name:8080"
  done

  services+="
  $hub_name:
    build:
      context: ../..
      dockerfile: packages/dfos-web-relay-go/Dockerfile
    environment:
      PORT: \"8080\"
      RELAY_NAME: \"$hub_name (hub)\"
      PEERS: \"$hub_peers\"
      SYNC_INTERVAL: \"$SYNC_INTERVAL\"
    ports:
      - \"$BASE_PORT:8080\"
    volumes:
      - data-$hub_name:/data
"
  volumes+="  data-$hub_name:
"

  # spokes peer only with hub
  for i in $(seq 2 "$count"); do
    local name="relay-$(printf '%02d' "$i")"
    local host_port=$((BASE_PORT + i - 1))

    services+="
  $name:
    build:
      context: ../..
      dockerfile: packages/dfos-web-relay-go/Dockerfile
    environment:
      PORT: \"8080\"
      RELAY_NAME: \"$name\"
      PEERS: \"http://$hub_name:8080\"
      SYNC_INTERVAL: \"$SYNC_INTERVAL\"
    ports:
      - \"$host_port:8080\"
    volumes:
      - data-$name:/data
"
    volumes+="  data-$name:
"
  done

  cat > "$COMPOSE_FILE" <<EOF
# Generated by topology.sh — star topology with $count nodes (hub: $hub_name)
services:
$services
volumes:
$volumes
EOF
}

# ---------------------------------------------------------------------------
# smoke test
# ---------------------------------------------------------------------------

smoke_test() {
  echo ""
  echo "=== smoke test ==="
  echo ""

  # discover running relays by scanning ports
  local ports=()
  for port in $(seq $BASE_PORT $((BASE_PORT + 19))); do
    if curl -sf "http://localhost:$port/.well-known/dfos-relay" >/dev/null 2>&1; then
      ports+=("$port")
    fi
  done

  if [ ${#ports[@]} -eq 0 ]; then
    echo "ERROR: no relays found on ports $BASE_PORT-$((BASE_PORT + 19))"
    exit 1
  fi

  echo "Found ${#ports[@]} relay(s): ${ports[*]}"

  # print DIDs
  for port in "${ports[@]}"; do
    local did
    did=$(curl -sf "http://localhost:$port/.well-known/dfos-relay" | python3 -c "import sys,json; print(json.load(sys.stdin)['did'])")
    echo "  :$port → $did"
  done

  # create a test identity on the first relay
  local target_port=${ports[0]}
  echo ""
  echo "Creating test identity on :$target_port..."

  # use the Go binary to generate a signed identity token
  local token
  token=$(cd "$SCRIPT_DIR" && go run ./cmd/gentoken 2>/dev/null || true)

  if [ -z "$token" ]; then
    echo "gentoken not available — using inline signing"
    # fall back: POST a pre-generated identity via the Go test helper
    # For now, just verify peering is wired by checking that each relay
    # can see the others' relay identities via read-through
    echo ""
    echo "Testing read-through: fetch relay-01 DID from other nodes..."
    local relay01_did
    relay01_did=$(curl -sf "http://localhost:${ports[0]}/.well-known/dfos-relay" | python3 -c "import sys,json; print(json.load(sys.stdin)['did'])")

    local pass=true
    for port in "${ports[@]:1}"; do
      local status
      status=$(curl -sf -o /dev/null -w "%{http_code}" "http://localhost:$port/identities/$relay01_did" 2>/dev/null || echo "000")
      if [ "$status" = "200" ]; then
        echo "  :$port → relay-01 identity found (read-through) ✓"
      else
        echo "  :$port → relay-01 identity NOT found (status: $status)"
        pass=false
      fi
    done

    # test sync: wait for sync interval and check if relay-01 can see relay-02
    if [ ${#ports[@]} -ge 2 ]; then
      local relay02_did
      relay02_did=$(curl -sf "http://localhost:${ports[1]}/.well-known/dfos-relay" | python3 -c "import sys,json; print(json.load(sys.stdin)['did'])")
      echo ""
      echo "Waiting for sync cycle (${SYNC_INTERVAL})..."
      sleep 6

      echo "Checking if relay-01 synced relay-02's identity..."
      local sync_status
      sync_status=$(curl -sf -o /dev/null -w "%{http_code}" "http://localhost:${ports[0]}/identities/$relay02_did" 2>/dev/null || echo "000")
      if [ "$sync_status" = "200" ]; then
        echo "  relay-01 has relay-02's identity via sync ✓"
      else
        echo "  relay-01 does NOT have relay-02's identity (status: $sync_status)"
        pass=false
      fi
    fi

    echo ""
    if [ "$pass" = true ]; then
      echo "=== SMOKE TEST PASSED ==="
    else
      echo "=== SMOKE TEST FAILED ==="
      exit 1
    fi
    return
  fi
}

# ---------------------------------------------------------------------------
# commands
# ---------------------------------------------------------------------------

wait_for_health() {
  local count=$1
  echo "Waiting for $count relay(s) to be healthy..."
  for i in $(seq 1 "$count"); do
    local port=$((BASE_PORT + i - 1))
    for attempt in $(seq 1 30); do
      if curl -sf "http://localhost:$port/.well-known/dfos-relay" >/dev/null 2>&1; then
        break
      fi
      if [ "$attempt" -eq 30 ]; then
        echo "ERROR: relay on port $port failed to start"
        exit 1
      fi
      sleep 1
    done
  done
  echo "All relays healthy."
}

cmd_up() {
  local topology=${1:-ring}
  local count=${2:-3}

  echo "Generating $topology topology with $count nodes..."

  case "$topology" in
    ring) generate_ring "$count" ;;
    mesh) generate_mesh "$count" ;;
    star) generate_star "$count" ;;
    *) echo "Unknown topology: $topology (use ring, mesh, or star)"; exit 1 ;;
  esac

  echo "Generated $COMPOSE_FILE"
  echo ""
  echo "Building and starting..."
  docker compose -f "$COMPOSE_FILE" build
  docker compose -f "$COMPOSE_FILE" up -d

  wait_for_health "$count"
  smoke_test
}

cmd_smoke() {
  smoke_test
}

cmd_down() {
  if [ -f "$COMPOSE_FILE" ]; then
    docker compose -f "$COMPOSE_FILE" down -v
    rm -f "$COMPOSE_FILE"
    echo "Topology torn down."
  else
    echo "No generated compose file found."
  fi
}

# ---------------------------------------------------------------------------
# main
# ---------------------------------------------------------------------------

case "${1:-ring}" in
  smoke) cmd_smoke ;;
  down)  cmd_down ;;
  *)     cmd_up "${1:-ring}" "${2:-3}" ;;
esac
