/*

  @metalabel/dfos-client/siwd

  Sign In With DFOS — the three load-bearing pieces of the challenge/response,
  and nothing more. The unlock is NOT a fat verifier; it is `siwdSigningInput`,
  the PURE byte contract both halves share. A browser wallet signs those exact
  bytes; a verifier re-derives them. Without it the challenge→JWS encoding lives
  nowhere and the two sides drift silently. See specs/SIWD.md.

  Verification follows SIWD.md §Third-Party Verification: the signing key MUST be
  a CURRENT `authKeys` entry of a non-deleted identity — rotated-out keys and
  deleted identities MUST NOT verify.

*/

import {
  buildSignRequest,
  decodeMultikey,
  encodeEd25519Multikey,
  signIdentityOperation,
  SignRequestVerifyError,
  verifyIdentityChain,
  verifySignRequest,
  type IdentityOperation,
  type MultikeyPublicKey,
  type Signer,
  type VerifiedIdentity,
  type VerifiedSignRequest,
} from '@metalabel/dfos-protocol/chain';
import {
  assertJwsProfile,
  base64urlDecode,
  base64urlEncode,
  createNewEd25519Keypair,
  decodeJwsUnsafe,
  generateId,
  generateIdNoPrefix,
  importEd25519Keypair,
  signPayloadEd25519,
  verifyJws,
} from '@metalabel/dfos-protocol/crypto';
import type { Client, VerifyResult } from './types';

// -----------------------------------------------------------------------------
// challenge
// -----------------------------------------------------------------------------

/**
 * The normative JWS header `typ` for a signed SIWD challenge (SIWD.md). Signers
 * MUST set it; `verifySiwd` rejects anything else — it is also what lets typ-
 * routing dispatchers tell a SIWD proof apart from credentials and chain ops.
 */
export const SIWD_JWS_TYP = 'did:dfos:siwd';

/**
 * The normative JWS header `typ` for a client ASK PROOF — the artifact a
 * loopback client signs to prove key control at ask-time, registered alongside
 * `SIWD_JWS_TYP` by SIWD.md §The ask proof.
 *
 * The two artifacts cover the SAME canonical challenge bytes, so the distinct
 * `typ` is the only thing keeping them from being fungible: without it, an ask
 * proof a client signed to open a consent screen would present as a subject's
 * sign-in for that same challenge, and a subject's sign-in would present as a
 * client's ask. The typ gate on each side is what scopes a signature to the
 * purpose it was produced for.
 */
export const SIWD_ASK_JWS_TYP = 'did:dfos:siwd-ask';

/** Allowed forward clock skew when validating challenge timestamps (seconds). */
const MAX_CLOCK_SKEW_SECONDS = 60;

export interface SiwdChallenge {
  /** Origin domain of the requesting application. */
  domain: string;
  /** Unique replay-prevention value generated by the third party. */
  nonce: string;
  /** ISO 8601 timestamp of challenge creation. */
  timestamp: string;
  /** Human-readable description shown on the consent screen. */
  statement?: string;
  /** Binds the challenge to a specific DID. */
  did?: string;
}

export interface SiwdSession {
  did: string;
  domain: string;
  nonce: string;
  timestamp: string;
  statement?: string;
  /** The DID URL of the key that signed the challenge. */
  kid: string;
}

const SIWD_CHALLENGE_FIELDS = new Set(['domain', 'nonce', 'timestamp', 'statement', 'did']);
const WHOLE_SECOND_TIMESTAMP = /^\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}\.000Z$/;
const LONE_SURROGATE = /[\uD800-\uDBFF](?![\uDC00-\uDFFF])|(?<![\uD800-\uDBFF])[\uDC00-\uDFFF]/;
const MAX_SIGN_REQUEST_WINDOW_SECONDS = 604_800;

const validateSiwdChallenge = (value: unknown): SiwdChallenge => {
  if (typeof value !== 'object' || value === null || Array.isArray(value)) {
    throw new Error('invalid SIWD challenge: expected a JSON object');
  }

  const raw = value as Record<string, unknown>;
  for (const field of Object.keys(raw)) {
    if (!SIWD_CHALLENGE_FIELDS.has(field)) {
      throw new Error(`invalid SIWD challenge: unknown member ${field}`);
    }
  }

  for (const field of ['domain', 'nonce', 'timestamp'] as const) {
    if (typeof raw[field] !== 'string' || raw[field].length === 0) {
      throw new Error(`invalid SIWD challenge: ${field} must be a non-empty string`);
    }
  }
  for (const field of ['statement', 'did'] as const) {
    if (raw[field] !== undefined && typeof raw[field] !== 'string') {
      throw new Error(`invalid SIWD challenge: ${field} must be a string when present`);
    }
  }

  const strings = [raw['domain'], raw['nonce'], raw['timestamp'], raw['statement'], raw['did']];
  if (strings.some((field) => typeof field === 'string' && LONE_SURROGATE.test(field))) {
    throw new Error('invalid SIWD challenge: string members must be well-formed Unicode');
  }

  const timestamp = raw['timestamp'] as string;
  const timestampMs = Date.parse(timestamp);
  if (
    !WHOLE_SECOND_TIMESTAMP.test(timestamp) ||
    Number.isNaN(timestampMs) ||
    new Date(timestampMs).toISOString() !== timestamp
  ) {
    throw new Error('invalid SIWD challenge: timestamp must be ISO-8601 UTC whole-second .000Z');
  }

  return {
    domain: raw['domain'] as string,
    nonce: raw['nonce'] as string,
    timestamp,
    ...(raw['statement'] !== undefined ? { statement: raw['statement'] as string } : {}),
    ...(raw['did'] !== undefined ? { did: raw['did'] as string } : {}),
  };
};

/**
 * The byte contract. Serializes a challenge to the canonical bytes that ARE the
 * JWS payload and the base64url query-param body — a fixed key order
 * (domain, nonce, timestamp, statement?, did?) so both halves agree exactly.
 * PURE and clientless: import it in an edge minter and in a browser wallet alike.
 */
export const siwdSigningInput = (challenge: SiwdChallenge): Uint8Array => {
  const parsed = validateSiwdChallenge(challenge);
  const canonical: Record<string, unknown> = {
    domain: parsed.domain,
    nonce: parsed.nonce,
    timestamp: parsed.timestamp,
  };
  if (parsed.statement !== undefined) canonical['statement'] = parsed.statement;
  if (parsed.did !== undefined) canonical['did'] = parsed.did;
  return new TextEncoder().encode(JSON.stringify(canonical));
};

/**
 * Parse exact SIWD challenge octets under the signer-side WYSIWYS contract.
 * The input must be UTF-8 JSON, satisfy the closed challenge schema, and equal
 * the canonical serialization byte for byte.
 */
export const parseSiwdChallenge = (octets: Uint8Array): SiwdChallenge => {
  let source: string;
  try {
    source = new TextDecoder('utf-8', { fatal: true }).decode(octets);
  } catch {
    throw new Error('invalid SIWD challenge: payload is not valid UTF-8 JSON');
  }
  if (source.startsWith('\uFEFF')) {
    throw new Error('invalid SIWD challenge: payload must not carry a UTF-8 BOM');
  }

  let raw: unknown;
  try {
    raw = JSON.parse(source);
  } catch {
    throw new Error('invalid SIWD challenge: payload is not valid JSON');
  }
  const challenge = validateSiwdChallenge(raw);
  const canonical = siwdSigningInput(challenge);
  if (
    canonical.length !== octets.length ||
    !canonical.every((byte, index) => byte === octets[index])
  ) {
    throw new Error('invalid SIWD challenge: payload bytes are not canonical');
  }
  return challenge;
};

export interface CreateChallengeInput {
  domain: string;
  statement?: string;
  did?: string;
  /** Provide a nonce, or one is generated. */
  nonce?: string;
  /** Provide a timestamp, or `now` is used. */
  timestamp?: string;
  /** Clock injection (unix ms) for the timestamp. Default `Date.now()`. */
  now?: () => number;
}

/**
 * Mint a challenge, clientless and edge-safe. Returns the challenge object, the
 * base64url `encoded` form for the `/authorize?challenge=` query param, and the
 * nonce for server-side replay storage. `encoded` is exactly
 * base64url(siwdSigningInput(challenge)) — the same bytes the wallet signs.
 */
export const createSiwdChallenge = (
  input: CreateChallengeInput,
): { challenge: SiwdChallenge; encoded: string; nonce: string } => {
  const nonce = input.nonce ?? generateIdNoPrefix();
  const timestampValue =
    input.timestamp ?? new Date(input.now ? input.now() : Date.now()).toISOString();
  const timestampMs = Date.parse(timestampValue);
  if (Number.isNaN(timestampMs)) {
    throw new Error(`invalid SIWD challenge: unparseable timestamp: ${timestampValue}`);
  }
  const timestamp = new Date(Math.floor(timestampMs / 1000) * 1000).toISOString();
  const challenge: SiwdChallenge = {
    domain: input.domain,
    nonce,
    timestamp,
    ...(input.statement !== undefined ? { statement: input.statement } : {}),
    ...(input.did !== undefined ? { did: input.did } : {}),
  };
  const encoded = base64urlEncode(siwdSigningInput(challenge));
  return { challenge, encoded, nonce };
};

/** Decode a base64url `challenge` query-param body back into a challenge object. */
export const decodeSiwdChallenge = (encoded: string): SiwdChallenge =>
  parseSiwdChallenge(base64urlDecode(encoded));

// -----------------------------------------------------------------------------
// profile A login kit
// -----------------------------------------------------------------------------

/**
 * Hostnames that make a redirect a LOOPBACK redirect — a CLI or a desktop app
 * listening on a local port. Exact matches only, because this set is what
 * CLASSIFIES a request into a tier, and the tiers have different rules:
 * `127.0.0.2` and `localhost.evil.example` are public domains that merely read
 * as local, and classifying one as loopback would hand a domain-holding site
 * the scope bound and the derived-domain treatment written for software that
 * holds no domain at all.
 */
const SIWD_LOOPBACK_HOSTS = new Set(['localhost', '127.0.0.1', '::1']);

/**
 * `URL.hostname` brackets an IPv6 literal because the brackets are URL grammar,
 * not part of the name — so `[::1]` and `::1` are the same host.
 */
const bareHostname = (url: URL): string => {
  const host = url.hostname.toLowerCase();
  return host.startsWith('[') && host.endsWith(']') ? host.slice(1, -1) : host;
};

const parseUrlOrThrow = (value: string, field: string): URL => {
  try {
    return new URL(value);
  } catch {
    throw new Error(`invalid SIWD login request: ${field} must be an absolute URL`);
  }
};

export interface SiwdLoginRequestInput {
  /** The host's authorize endpoint, e.g. `https://app.example.com/authorize`. */
  authorizeUrl: string;
  /** The RP's own domain — bound into the signed challenge as a bare hostname. */
  domain: string;
  /** Exact redirect target; must match the RP's registered or served allowlist. */
  redirectUri: string;
  /**
   * Requested scope: a space-separated SET of scope tokens (the OAuth `scope`
   * convention), each of which must be one specs/SIWD.md §Scopes and Credentials
   * registers. A request naming an unregistered token is refused WHOLE rather
   * than partially honored — a consent screen that silently dropped a token
   * would describe something other than what was asked for.
   */
  scope: string;
  /** Consent-screen prose. A host MAY decline to render it; see specs/SIWD.md. */
  statement?: string;
  /**
   * Bind the challenge to ONE identity — "sign in as this DID, or not at all".
   * Threaded into the signed bytes AND into `expect`, because binding a
   * challenge without verifying the binding proves nothing: a host that ignored
   * it would return a signature from whoever was logged in, and an RP checking
   * only the signature would accept it.
   */
  did?: string;
  /**
   * The RP's own DID. Rides through on a loopback redirect too, but a host
   * honors it there only under the loopback credential tier — see
   * `createSiwdLoopbackLoginRequest`, which adds the proof that backs it.
   */
  clientDid?: string;
  /** Supply a nonce minted elsewhere (e.g. by your backend); default: minted here. */
  nonce?: string;
}

export interface SiwdLoginRequest {
  /** Navigate the browser here, or hand it to the user. */
  url: string;
  /**
   * THE THING TO PERSIST ACROSS THE REDIRECT. One JSON-serializable object that
   * satisfies `SiwdExpectations`, so the whole round trip is: store this before
   * navigating, rehydrate it when the callback lands, and hand it straight to
   * `verifySiwd(client, jws, saved)`. Nothing else has to survive the hop, and
   * nothing has to be threaded to both ends by hand — which is the point, since
   * a `domain` or `did` that drifts between mint and verify is a check that
   * silently stops checking.
   *
   * SINGLE USE: consume the nonce on the way back, pass or fail. A backend
   * holding its minted nonces in shared state should hand `verifySiwd` a
   * `consumeNonce` instead of this object's `nonce`, so the consumption is
   * atomic and is the last thing that happens before a session is granted.
   *
   * WHOEVER VERIFIES MUST HAVE MINTED. A verifier that accepts an expectation
   * supplied by the party presenting the JWS is comparing a value against
   * itself and has verified nothing — the replay guard binds only when the
   * expectation comes from the verifier's own prior state (this object, held
   * server-side or in the session that began the sign-in) or from an
   * independent validation of it.
   *
   * `nonce` is REQUIRED here even though `SiwdExpectations` leaves it optional
   * for the `consumeNonce` form: what this function mints into the challenge is
   * always a string, and an RP persisting this object must get it back.
   */
  expect: Pick<SiwdExpectations, 'domain' | 'did'> & { nonce: string };
  /** base64url canonical challenge bytes, exactly as embedded in `url`. */
  challenge: string;
  /** ISO whole-second mint timestamp, exactly as embedded in the signed bytes. */
  timestamp: string;
}

/**
 * Mint a challenge and build the `/authorize` URL to send the browser to — the
 * OUTBOUND half of profile A. `readSiwdCallback` is the inbound half, and
 * `verifySiwd` is what both compose around: mint → redirect, read → verify.
 *
 * The rule this function owns is the LOOPBACK RULE, and what it turns on is
 * whether the request names a client identity. A bare `client_did` from an app
 * on a local port used to be refused outright — there is no domain serving a
 * well-known and no registration to check, so nothing backed the DID and a host
 * would not display an identity it could not stand behind. The LOOPBACK
 * CREDENTIAL TIER (specs/SIWD.md §Loopback Clients) replaces "nothing backs it"
 * with the one thing local software can prove: control of that identity's
 * current keys. So the param now rides through on a loopback redirect instead
 * of being dropped — but it is honored only when the request ALSO carries an
 * ask proof and, unless the DID is already resident on the host, the client's
 * identity chain. `createSiwdLoopbackLoginRequest` composes all three; a
 * `clientDid` passed to this function alone is an unbacked assertion the host
 * will refuse.
 *
 * The same judgment BOUNDS THE SCOPE. Every scope past `identity` returns a
 * credential issued to a `client_did`, so a loopback request with no client
 * identity at all still has nothing to issue to and specs/SIWD.md admits it for
 * `scope=identity` only — there is nothing to downgrade, so it throws. With a
 * client identity the tier is open and every scope is available.
 *
 * It also owns the WIRE PARAM NAMES (`challenge`, `redirect_uri`, `scope`,
 * `client_did`, and — via `createSiwdLoopbackLoginRequest` — `client_proof` and
 * `client_chain`) as their single source in this package. They are snake_case
 * on the wire and camelCase everywhere else, which is exactly the kind of seam
 * every hand-rolled RP re-implements and eventually gets wrong.
 *
 * PURE: no DOM, no storage, no navigation, no fetch — identical in a browser
 * and in Node. Throws on an unparseable `authorizeUrl` or `redirectUri`, and on
 * a non-`identity` scope over a loopback redirect with no client identity,
 * because those are mistakes in the RP's own configuration rather than runtime
 * conditions a result type would help a caller recover from.
 */
export const createSiwdLoginRequest = (input: SiwdLoginRequestInput): SiwdLoginRequest => {
  const authorizeUrl = parseUrlOrThrow(input.authorizeUrl, 'authorizeUrl');
  const redirect = parseUrlOrThrow(input.redirectUri, 'redirectUri');
  const isLoopback = SIWD_LOOPBACK_HOSTS.has(bareHostname(redirect));
  if (isLoopback && input.scope !== 'identity' && input.clientDid === undefined) {
    throw new Error(
      'invalid SIWD login request: loopback redirects support scope=identity only without a ' +
        'client identity — a credential scope needs a client_did proven under the loopback ' +
        'credential tier (specs/SIWD.md §Loopback Clients)',
    );
  }

  const { challenge, encoded, nonce } = createSiwdChallenge({
    domain: input.domain,
    ...(input.statement !== undefined ? { statement: input.statement } : {}),
    ...(input.did !== undefined ? { did: input.did } : {}),
    ...(input.nonce !== undefined ? { nonce: input.nonce } : {}),
  });

  // Built on a COPY of the parsed authorize URL so any query the host endpoint
  // already carries survives instead of being clobbered by concatenation.
  const url = new URL(authorizeUrl);
  url.searchParams.set('challenge', encoded);
  url.searchParams.set('redirect_uri', input.redirectUri);
  url.searchParams.set('scope', input.scope);
  if (input.clientDid !== undefined) {
    url.searchParams.set('client_did', input.clientDid);
  }

  return {
    url: url.toString(),
    expect: {
      domain: input.domain,
      nonce,
      ...(input.did !== undefined ? { did: input.did } : {}),
    },
    challenge: encoded,
    timestamp: challenge.timestamp,
  };
};

// -----------------------------------------------------------------------------
// loopback credential tier
// -----------------------------------------------------------------------------

/**
 * Sign the ask proof for a loopback authorize request: a JWS over the exact
 * canonical bytes of the request's own challenge, under `SIWD_ASK_JWS_TYP`,
 * signed by a CURRENT auth key of the client identity's chain (SIWD.md §The ask
 * proof). It is what makes a `client_did` on a loopback request mean something
 * — the host verifies it against the chain's current state before rendering any
 * consent, so key control is established at ask-time, not just at spend-time.
 *
 * BYTE-PRECISE, and deliberately not built with `createJws`. The host compares
 * the proof's payload SEGMENT by string equality against its own re-derivation
 * of `base64url(siwdSigningInput(challenge))`; a construction that round-tripped
 * the challenge through a JSON object would re-serialize it, and any spelling
 * that differed from the canonical one by a single byte would fail that
 * comparison while looking correct here. So this signs the `siwdSigningInput`
 * output directly.
 *
 * `kid` is the DID URL of the signing key. The host ignores it for key
 * SELECTION — it tries the chain's current auth keys — but it is set honestly
 * because a proof that names a key it was not signed with is a lie the wire
 * format has no reason to carry.
 *
 * The `client_proof` param that carries this is the REFERENCE wire surface, not
 * a normative name: SIWD.md defers how the ask proof travels to the hosted
 * endpoint's reference implementation, exactly as it does the endpoint itself.
 * What is normative is that it arrives WITH the ask and verifies BEFORE any
 * consent is rendered.
 */
export const signSiwdAskProof = async (input: {
  challenge: SiwdChallenge;
  /** DID URL of the signing key: `<did>#<keyId>`. Must be a CURRENT auth key. */
  kid: string;
  signer: Signer;
}): Promise<string> => {
  // Both halves must be present: `#x`, `x#`, and a bare `#` name no key, no
  // identity, or neither, and a host cannot resolve any of them to a chain.
  const hashIdx = input.kid.indexOf('#');
  if (hashIdx <= 0 || hashIdx === input.kid.length - 1) {
    throw new Error(
      'invalid SIWD ask proof: kid must be a DID URL with both halves non-empty (<did>#<keyId>)',
    );
  }
  const headerB64 = base64urlEncode(
    JSON.stringify({ alg: 'EdDSA', typ: SIWD_ASK_JWS_TYP, kid: input.kid }),
  );
  const payloadB64 = base64urlEncode(siwdSigningInput(input.challenge));
  const signingInput = `${headerB64}.${payloadB64}`;
  const signature = await input.signer(new TextEncoder().encode(signingInput));
  return `${signingInput}.${base64urlEncode(signature)}`;
};

/** SIWD.md carriage cap — an identity that has outgrown it has outgrown carriage. */
export const MAX_SIWD_CLIENT_CHAIN_OPS = 100;

/**
 * Encode a client identity chain for carriage on the authorize request: the
 * FULL ordered operation log, genesis first, as base64url of its JSON array —
 * the same grammar as the `challenge` param, so one decoder shape serves both.
 *
 * THIS IS THE LOOPBACK CARRIAGE FORM, and only that. An application that holds a
 * domain encodes nothing: it publishes the very same log as the raw JSON array
 * of the `identity_chain` member of its `/.well-known/dfos-app.json` app
 * description (SIWD.md §`identity_chain` — chain carriage), where the origin
 * serving the file is what associates the domain with the DID. Same chain, same
 * carriage rules — a URL is simply the carrier available to software that holds
 * no origin to publish from.
 *
 * The DID derived from the genesis operation MUST equal the `client_did` the
 * request names; a request where the two disagree makes no claim at all and the
 * host refuses it WHOLE rather than ingesting the chain and ignoring the
 * mismatch (SIWD.md §Chain residence). Carriage is only needed when the DID is
 * not already resident on the verifying host.
 *
 * The 100-operation cap is spec-normative and enforced here. Hosts MAY
 * additionally bound the ENCODED size for URL-transport reasons — the reference
 * host refuses carriages over 8KiB — which is transport policy rather than
 * protocol, so it is not a client-side throw; the practical reading is that a
 * chain anywhere near the op cap belongs on relays, not in a URL.
 *
 * As with the ask proof, the `client_chain` param is the REFERENCE wire surface
 * rather than a normative name — SIWD.md leaves the carriage encoding to the
 * hosted endpoint's reference implementation and pins only that the chain
 * arrives with the ask and verifies before any consent is rendered.
 */
export const encodeSiwdClientChain = (log: string[]): string => {
  if (!Array.isArray(log)) {
    throw new Error('invalid SIWD client chain: expected an array of identity-op JWS strings');
  }
  if (log.length === 0) {
    throw new Error('invalid SIWD client chain: log is empty — carriage needs the full log');
  }
  if (log.length > MAX_SIWD_CLIENT_CHAIN_OPS) {
    throw new Error(
      `invalid SIWD client chain: ${log.length} operations exceeds the ` +
        `${MAX_SIWD_CLIENT_CHAIN_OPS}-operation carriage cap`,
    );
  }
  if (log.some((operation) => typeof operation !== 'string' || operation.length === 0)) {
    throw new Error(
      'invalid SIWD client chain: every member must be a non-empty identity-op JWS string',
    );
  }
  return base64urlEncode(JSON.stringify(log));
};

export interface SiwdClientIdentity {
  did: string;
  /**
   * Verbatim identity-op JWS log, genesis first. A loopback client feeds it to
   * `encodeSiwdClientChain` to carry on the authorize URL; an application that
   * holds a domain serves this same array verbatim as the `identity_chain`
   * member of its app description document.
   */
  chain: string[];
  /** DID URL of the current auth key — feed to signSiwdAskProof. */
  kid: string;
  signer: Signer;
  /** Raw Ed25519 private key — persist it (with `chain`) to keep this DID across runs. */
  privateKey: Uint8Array;
}

/**
 * Mint a fresh client identity: one Ed25519 keypair and a single genesis
 * `create` operation naming it as the auth, assertion, and controller key. That
 * is an entire application identity — a DID whose key control is provable, and a
 * one-operation chain small enough to travel anywhere a chain has to travel.
 *
 * TIER-AGNOSTIC. What comes back is an ordinary DFOS identity, not a
 * loopback-only artifact; the tier is a property of how the identity is
 * PRESENTED, not of the identity itself. An application that holds a domain
 * serves `chain` verbatim as the `identity_chain` member of its
 * `/.well-known/dfos-app.json` app description and names `did` as its
 * `client_did` there; a loopback client carries the same chain on the authorize
 * request instead (`createSiwdLoopbackLoginRequest`), because it has no origin
 * to publish from. Both are minted here.
 *
 * KEY CUSTODY IS THE CALLER'S, and the identity is only as durable as the
 * custody: persist `privateKey` and `chain` — an OS keychain, a file the caller
 * protects — and hand them back to `restoreSiwdClientIdentity` on the next run.
 * That is the other half of this function, and it is not optional in practice.
 * A client that re-mints instead of restoring arrives as a DIFFERENT DID every
 * time, so every run asks the user to consent again and every credential the
 * last run earned belongs to an identity nothing will ever present again.
 * Nothing here touches storage; where the key lives is the caller's to decide.
 */
export const mintSiwdClientIdentity = async (): Promise<SiwdClientIdentity> => {
  const keypair = createNewEd25519Keypair();
  const keyId = generateId('key');
  const key: MultikeyPublicKey = {
    id: keyId,
    type: 'Multikey',
    publicKeyMultibase: encodeEd25519Multikey(keypair.publicKey),
  };
  const signer: Signer = async (message) => signPayloadEd25519(message, keypair.privateKey);

  const genesis: IdentityOperation = {
    version: 1,
    type: 'create',
    authKeys: [key],
    assertKeys: [key],
    controllerKeys: [key],
    createdAt: new Date(Math.floor(Date.now() / 1000) * 1000).toISOString(),
  };
  // genesis is signed with a BARE keyId: the DID is derived from this very
  // operation's CID, so there is no DID yet to build a DID URL from.
  const { jwsToken } = await signIdentityOperation({ operation: genesis, signer, keyId });
  const { did } = await verifyIdentityChain({ didPrefix: 'did:dfos', log: [jwsToken] });

  return {
    did,
    chain: [jwsToken],
    kid: `${did}#${keyId}`,
    signer,
    privateKey: keypair.privateKey,
  };
};

/**
 * Rebuild a client identity from what a previous run persisted — the other half
 * of `mintSiwdClientIdentity`, and what makes the DID (and the consent it
 * earned) survive across runs.
 *
 * It re-derives the public key from `privateKey` and finds the CURRENT auth key
 * of the verified chain that key belongs to, which is the same currency rule the
 * host applies to the ask proof. A key that has been ROTATED OUT of the chain
 * therefore refuses to restore rather than producing an identity whose proofs
 * would be rejected at the far end: failing here, with the reason in hand, is
 * strictly better than failing after a redirect. The `kid` comes from the chain
 * rather than from storage for the same reason — the chain is the authority on
 * which key is current, and a persisted `kid` is a guess that ages.
 *
 * `chain` is the caller's stored log, and it is verified here, so a corrupted or
 * truncated log surfaces as a throw rather than as a silently wrong DID.
 */
export const restoreSiwdClientIdentity = async (input: {
  privateKey: Uint8Array;
  /** The verbatim log `mintSiwdClientIdentity` returned, genesis first. */
  chain: string[];
}): Promise<SiwdClientIdentity> => {
  const keypair = importEd25519Keypair(input.privateKey);
  const identity = await verifyIdentityChain({ didPrefix: 'did:dfos', log: input.chain });

  const authKey = identity.authKeys.find((key) => {
    const keyBytes = decodeMultikey(key.publicKeyMultibase).keyBytes;
    return (
      keyBytes.length === keypair.publicKey.length &&
      keyBytes.every((byte, index) => byte === keypair.publicKey[index])
    );
  });
  if (!authKey) {
    throw new Error(
      'invalid SIWD client identity: the private key is not a CURRENT authentication key of ' +
        'the supplied chain — a rotated-out key cannot restore, because the host would refuse ' +
        'the ask proof it signs',
    );
  }

  return {
    did: identity.did,
    chain: input.chain,
    kid: `${identity.did}#${authKey.id}`,
    signer: async (message) => signPayloadEd25519(message, keypair.privateKey),
    privateKey: input.privateKey,
  };
};

export interface SiwdLoopbackLoginRequestInput {
  /** The host's authorize endpoint, e.g. `https://app.example.com/authorize`. */
  authorizeUrl: string;
  /** Loopback redirect target — `http://` on localhost / 127.0.0.1 / [::1], any port/path. */
  redirectUri: string;
  /**
   * Requested scope, in the same space-separated set form as
   * `SiwdLoginRequestInput.scope`. Naming a client identity opens the tier, so
   * every scope the HOST offers is available here — the `identity`-only bound
   * belongs to the anonymous loopback shape, which has no `client_did` to issue
   * a credential to.
   */
  scope: string;
  /** Consent-screen prose. A host MAY decline to render it; see specs/SIWD.md. */
  statement?: string;
  /** Bind the challenge to ONE subject DID (sign in as this DID or not at all). */
  did?: string;
  /** The client identity asking under the loopback credential tier. */
  client: Pick<SiwdClientIdentity, 'did' | 'kid' | 'signer'> & {
    /** Verbatim chain to carry; omit when the DID is already resident on the host. */
    chain?: string[];
  };
  /** Supply a nonce minted elsewhere; default: minted here. Verify against it. */
  nonce?: string;
}

/**
 * Build a loopback authorize URL under the LOOPBACK CREDENTIAL TIER — the
 * outbound half of what `createSiwdLoginRequest` alone cannot produce. It is
 * that function plus the two things that back the `client_did` it now carries:
 * an ask proof (SIWD.md §The ask proof) and, unless the DID is already resident
 * on the host, the client's identity chain (SIWD.md §Chain residence).
 *
 * `domain` is DERIVED, not accepted. SIWD.md pins a loopback challenge's domain
 * to the BARE loopback host — the port is not part of the binding, because a
 * local application cannot reserve one — and the host compares that value
 * literally against the redirect's host. Taking a `domain` input here would be
 * an invitation to a mismatch that fails only after the redirect.
 *
 * WHAT THIS PROVES IS KEY CONTROL, NOT PROVENANCE. The chain says which keys
 * the asking party holds; nothing about a loopback client's origin or authorship
 * is checkable, and the host's consent screen says exactly that rather than
 * displaying a domain it cannot stand behind. The residue is bounded on the
 * other side: a credential minted to a loopback client carries a hard expiry
 * ceiling — RECOMMENDED 14 days — so a proven-but-unvouched-for client's grant
 * ages out on its own, with revocation remaining the user's real disconnect.
 *
 * Async (it signs) and throwing on configuration errors — a `redirectUri` that
 * is not an `http://` loopback target, a `kid` that does not belong to the
 * client's own DID, a chain past the carriage cap — consistent with the
 * constructor half of this module.
 */
export const createSiwdLoopbackLoginRequest = async (
  input: SiwdLoopbackLoginRequestInput,
): Promise<SiwdLoginRequest> => {
  const redirect = parseUrlOrThrow(input.redirectUri, 'redirectUri');
  const domain = bareHostname(redirect);
  // SIWD.md defines the loopback interface as `http://` on these hosts. The
  // scheme is pinned HERE rather than in the general classifier because this
  // entrypoint is the one that asserts "I am local software": an `https://` or
  // `ftp://` target on a loopback name is a misconfiguration, not a tier.
  if (!SIWD_LOOPBACK_HOSTS.has(domain) || redirect.protocol !== 'http:') {
    throw new Error(
      'invalid SIWD login request: redirectUri must be an http:// loopback target ' +
        '(localhost, 127.0.0.1, [::1])',
    );
  }
  // A kid outside the client's own DID cannot resolve against the chain the
  // request carries, so the host would refuse it — cheaper to say so now than
  // after a redirect. Whether the key is CURRENT is the host's call (and
  // `restoreSiwdClientIdentity`'s), not something to re-verify here.
  if (!input.client.kid.startsWith(`${input.client.did}#`)) {
    throw new Error(
      'invalid SIWD login request: client.kid must be a DID URL of client.did (<did>#<keyId>)',
    );
  }

  const request = createSiwdLoginRequest({
    authorizeUrl: input.authorizeUrl,
    domain,
    redirectUri: input.redirectUri,
    scope: input.scope,
    clientDid: input.client.did,
    ...(input.statement !== undefined ? { statement: input.statement } : {}),
    ...(input.did !== undefined ? { did: input.did } : {}),
    ...(input.nonce !== undefined ? { nonce: input.nonce } : {}),
  });

  // Sign the challenge the URL actually carries, recovered from the param
  // itself: the proof and the request must cover the same bytes, and deriving
  // them twice from the same input is how they would silently stop matching.
  const proof = await signSiwdAskProof({
    challenge: decodeSiwdChallenge(request.challenge),
    kid: input.client.kid,
    signer: input.client.signer,
  });

  const url = new URL(request.url);
  url.searchParams.set('client_proof', proof);
  if (input.client.chain !== undefined) {
    url.searchParams.set('client_chain', encodeSiwdClientChain(input.client.chain));
  }

  return { ...request, url: url.toString() };
};

// -----------------------------------------------------------------------------
// profile A callback
// -----------------------------------------------------------------------------

/**
 * What came back on the redirect. `none` means this was a plain page load, not
 * a callback at all — the common case on an RP's own landing page.
 */
export type SiwdCallbackResult =
  | {
      kind: 'success';
      jws: string;
      did: string;
      /** Present only when the host minted one and the input carried a fragment. */
      credential?: string;
    }
  | { kind: 'denied'; error: string }
  | { kind: 'none' };

/** An empty value carries no more information than an absent one. */
const callbackParam = (params: URLSearchParams, key: string): string | undefined => {
  const value = params.get(key);
  return value === null || value === '' ? undefined : value;
};

/**
 * Accept the three things a caller actually has in hand: a full URL, a `URL`,
 * or a bare query string — `location.search` is what a browser RP reaches for,
 * and it is `''` on a plain page load, which must read as "no callback" rather
 * than blow up on the most common path through the function.
 *
 * The bare-string form SPLITS ON THE FIRST `#` itself, because
 * `URLSearchParams` does not treat `#` as a delimiter: a caller who reached for
 * `location.search + location.hash` — the natural reach once the docs say the
 * credential is in the fragment — would otherwise get the whole fragment glued
 * onto the last query value, silently corrupting `did` into
 * `did:dfos:x#credential=…` rather than failing. `fragment` stays ABSENT when
 * there is none, rather than empty: there was nothing to have looked in.
 *
 * The host serializes the fragment with `URLSearchParams`, so it is parsed with
 * the same thing.
 */
const callbackParts = (
  url: string | URL,
): { query: URLSearchParams; fragment?: URLSearchParams } => {
  if (typeof url === 'string' && (url === '' || url.startsWith('?'))) {
    const hashIdx = url.indexOf('#');
    const hash = hashIdx < 0 ? '' : url.slice(hashIdx + 1);
    return {
      query: new URLSearchParams(hashIdx < 0 ? url : url.slice(0, hashIdx)),
      ...(hash !== '' ? { fragment: new URLSearchParams(hash) } : {}),
    };
  }
  const parsed = typeof url === 'string' ? parseUrlOrThrow(url, 'url') : url;
  const hash = parsed.hash.startsWith('#') ? parsed.hash.slice(1) : parsed.hash;
  return {
    query: parsed.searchParams,
    ...(hash !== '' ? { fragment: new URLSearchParams(hash) } : {}),
  };
};

/**
 * Read a profile-A callback — the INBOUND half of the pair. Pure parse: it
 * decides only what kind of return this is, and hands `jws` to the caller for
 * `verifySiwd`. NOTHING here is trusted; the `did` param is unauthenticated
 * courier convenience, and the DID a caller should act on is the one
 * `verifySiwd` returns from the signature.
 *
 * Takes an absolute URL string, a `URL`, or a bare `?…` query string (so
 * `readSiwdCallback(location.search)` works, including when it is empty).
 *
 * A CREDENTIAL COMES BACK IN THE FRAGMENT, and that is a deliberate asymmetry
 * with `jws`/`did`, which ride the query. A fragment is never sent to a server:
 * it lands in no access log, no proxy log, and no `Referer` header, so the one
 * artifact that is redeemable outside this channel is the one that stays on the
 * client. Reading it therefore requires the WHOLE URL — `location.href`, not
 * `location.search`.
 *
 * THAT SAME PROPERTY IS A PROBLEM FOR A CLI, and this tier's primary consumer is
 * a CLI. A browser does not send the fragment to the loopback listener either,
 * so the request line a local HTTP server sees carries the query and nothing
 * else. The standard resolution (SIWD.md §4's loopback note) is for the listener
 * to answer with a small page whose script reads `location.href` and posts the
 * whole URL back to the local server; feed THAT to this function. A browser RP
 * passes `location.href` directly and needs no relay.
 *
 * SCRUB THE URL YOURSELF, IMMEDIATELY. The signed JWS in the query string is in
 * the address bar, in `history`, in the referrer of anything the page loads
 * next, and in any analytics that samples the location; a credential in the
 * fragment is spared the referrer and the server-side logs but is in the address
 * bar and `history` just the same. This function cannot do the scrubbing for you
 * — `history` is environment-owned and this package stays free of the DOM — so a
 * browser RP should follow the read with a `history.replaceState` back to the
 * bare path, which clears both halves.
 *
 * A HALF-CALLBACK IS A FAILURE, NOT A NON-EVENT: `jws` without `did` (or the
 * reverse) resolves to `denied` carrying a synthetic reason rather than `none`.
 * Silently treating it as a plain page load would strand the user on a
 * sign-in button with no explanation of why the last attempt vanished.
 *
 * THE QUERY HALF'S VERDICT WINS. A credential in the fragment is lifted only
 * onto a `success`, never on its own: a `denied` or `none` stays exactly what
 * it was. There is no half-callback state a stray fragment could promote —
 * a fragment on a non-callback page load is noise, not a session.
 */
export const readSiwdCallback = (url: string | URL): SiwdCallbackResult => {
  const { query, fragment } = callbackParts(url);
  const jws = callbackParam(query, 'jws');
  const did = callbackParam(query, 'did');
  const error = callbackParam(query, 'error');

  if (jws !== undefined && did !== undefined) {
    const credential = fragment ? callbackParam(fragment, 'credential') : undefined;
    return { kind: 'success', jws, did, ...(credential !== undefined ? { credential } : {}) };
  }
  if (error !== undefined) return { kind: 'denied', error };
  if (jws !== undefined) return { kind: 'denied', error: 'malformed SIWD callback: missing did' };
  if (did !== undefined) return { kind: 'denied', error: 'malformed SIWD callback: missing jws' };
  return { kind: 'none' };
};

// -----------------------------------------------------------------------------
// sign-request profile B
// -----------------------------------------------------------------------------

export interface BuildSiwdSignRequestInput {
  /** Requester DID that signs the courier envelope. */
  did: string;
  /** DID being asked to sign the SIWD artifact. */
  subject: string;
  challenge: SiwdChallenge;
  /** Explicit composer policy; no implicit SIWD mailbox lifetime exists. */
  acceptanceWindowSeconds: number;
  expiresAt: string;
  createdAt?: string;
  signer: Signer;
  keyId: string;
}

export interface ValidateSiwdSignRequestOptions {
  signerDid: string;
  /** Must be the composer's stated acceptance policy for this request. */
  acceptanceWindowSeconds: number;
  resolveIdentity: (did: string) => Promise<VerifiedIdentity | undefined>;
  /** Unix milliseconds; defaults to Date.now(). */
  now?: number;
}

export interface ValidatedSiwdSignRequest extends VerifiedSignRequest {
  /** Strictly parsed canonical challenge used by the signer for rendering. */
  challenge: SiwdChallenge;
}

const assertSiwdAcceptanceWindow = (seconds: number): void => {
  if (!Number.isSafeInteger(seconds) || seconds <= 0) {
    throw new Error('SIWD acceptanceWindowSeconds must be a positive integer');
  }
  if (seconds > MAX_SIGN_REQUEST_WINDOW_SECONDS) {
    throw new Error('SIWD acceptanceWindowSeconds exceeds the sign-request 604800-second ceiling');
  }
};

const assertSiwdOneClock = (
  challengeTimestamp: string,
  expiresAt: string,
  acceptanceWindowSeconds: number,
): void => {
  assertSiwdAcceptanceWindow(acceptanceWindowSeconds);
  const challengeMs = Date.parse(challengeTimestamp);
  const expiresMs = Date.parse(expiresAt);
  if (Number.isNaN(expiresMs)) {
    throw new Error(`invalid SIWD sign request: unparseable expiresAt: ${expiresAt}`);
  }
  const normalizedExpiresMs = Math.floor(expiresMs / 1000) * 1000;
  if (normalizedExpiresMs > challengeMs + acceptanceWindowSeconds * 1000) {
    throw new Error('SIWD sign request expiresAt exceeds the challenge acceptance window');
  }
};

/** Compose SIWD profile B using the generic sign-request envelope. */
export const buildSiwdSignRequest = async (
  input: BuildSiwdSignRequestInput,
): Promise<{ jwsToken: string; requestCID: string }> => {
  const challenge = validateSiwdChallenge(input.challenge);
  if (challenge.did !== undefined && challenge.did !== input.subject) {
    throw new Error('SIWD challenge did does not match sign request subject');
  }
  assertSiwdOneClock(challenge.timestamp, input.expiresAt, input.acceptanceWindowSeconds);
  return buildSignRequest({
    did: input.did,
    subject: input.subject,
    payloadTyp: SIWD_JWS_TYP,
    payload: siwdSigningInput(challenge),
    expiresAt: input.expiresAt,
    ...(input.createdAt !== undefined ? { createdAt: input.createdAt } : {}),
    signer: input.signer,
    keyId: input.keyId,
  });
};

/** Verify and strictly parse a SIWD profile-B request before rendering/signing. */
export const validateSiwdSignRequest = async (
  jwsToken: string,
  options: ValidateSiwdSignRequestOptions,
): Promise<ValidatedSiwdSignRequest> => {
  assertSiwdAcceptanceWindow(options.acceptanceWindowSeconds);
  const request = await verifySignRequest(jwsToken, {
    resolveIdentity: options.resolveIdentity,
    ...(options.now !== undefined ? { now: options.now } : {}),
  });
  // Every post-envelope family gate is a definitive "invalid" verdict — wrap in
  // the sign-request error taxonomy so consumers branch on `reason`, matching
  // the Go twin (ErrSignRequestInvalid), never on message text.
  const invalid = (message: string) => new SignRequestVerifyError('invalid', message);
  if (request.subject !== options.signerDid) {
    throw invalid('SIWD sign request subject does not match signer DID');
  }
  if (request.payloadTyp !== SIWD_JWS_TYP) {
    throw invalid(`invalid SIWD sign request payloadTyp: ${request.payloadTyp}`);
  }
  let challenge: SiwdChallenge;
  try {
    challenge = parseSiwdChallenge(request.payloadBytes);
    assertSiwdOneClock(challenge.timestamp, request.expiresAt, options.acceptanceWindowSeconds);
  } catch (err) {
    throw invalid(err instanceof Error ? err.message : 'invalid SIWD sign request payload');
  }
  if (challenge.did !== undefined && challenge.did !== options.signerDid) {
    throw invalid('SIWD challenge did does not match signer DID');
  }
  return { ...request, challenge };
};

// -----------------------------------------------------------------------------
// verify
// -----------------------------------------------------------------------------

export interface SiwdExpectations {
  /** The verifier's own origin — MUST match the challenge domain. */
  domain: string;
  /**
   * The nonce this verifier issued for the session. Supply EXACTLY ONE of
   * `nonce` and `consumeNonce`.
   */
  nonce?: string;
  /**
   * Atomically consume the presented nonce against verifier-minted state — a
   * Redis `GETDEL`, a `DELETE … RETURNING` row — returning true iff THIS
   * verifier minted it and it was unspent. Membership in the verifier's own
   * minted state is what proves the verifier minted it, which is the whole
   * check; an equality test against a `nonce` fed in from the presented
   * artifact is a value compared against itself. The ATOMICITY is yours: a
   * get-then-delete lets two concurrent replays both win.
   *
   * Called AT MOST ONCE, and only after every other check has passed —
   * signature, current-key resolution, did binding, domain, timestamp — so an
   * otherwise-invalid presentation can never burn a live nonce, and the
   * consumption is the last gate before the caller grants anything.
   */
  consumeNonce?: (nonce: string) => boolean | Promise<boolean>;
  /** If set, the challenge (and identity) MUST bind to this DID. */
  did?: string;
  /** If set, the signed challenge's timestamp MUST equal this exact value. */
  timestamp?: string;
  /** Reject challenges older than this many seconds. Default 300 (5 min). */
  maxAgeSeconds?: number;
  /**
   * Accept an identity resolution whose tip could not be verified (cache-only
   * or empty-delta-against-cache). Default FALSE: authentication never silently
   * degrades — a rotated-out key must not verify against a stale cached state.
   */
  allowStale?: boolean;
  /** Clock injection (unix ms). Default `Date.now()`. */
  now?: () => number;
}

const fail = (error: string): VerifyResult<SiwdSession> => ({ ok: false, error });

/**
 * Verify a SIWD challenge JWS. No-throw. The signature is checked under the DFOS
 * profile (via the protocol's `verifyJws`), against a CURRENT `authKeys` entry
 * of a non-deleted identity resolved through the client. Nonce, timestamp
 * window, and domain are validated against `expect`.
 */
export const verifySiwd = async (
  client: Client,
  jws: string,
  expect: SiwdExpectations,
): Promise<VerifyResult<SiwdSession>> => {
  try {
    // one nonce discipline, chosen up front: both forms configured is two
    // answers to one question, neither is no replay defense at all. A
    // configuration error rather than a bad artifact — but this verifier does
    // not throw, so it comes back as a verdict like everything else.
    if ((expect.nonce === undefined) === (expect.consumeNonce === undefined)) {
      return fail('provide exactly one of nonce or consumeNonce');
    }

    const decoded = decodeJwsUnsafe(jws);
    if (!decoded) return fail('failed to decode JWS');

    const rawHeader = decoded.header as unknown;
    if (typeof rawHeader !== 'object' || rawHeader === null || Array.isArray(rawHeader)) {
      return fail('SIWD protected header must be an object');
    }
    assertJwsProfile(rawHeader as Record<string, unknown>, (message) => new Error(message));

    // typ gate — normative per SIWD.md; also what client.verify() routes on
    if (decoded.header.typ !== SIWD_JWS_TYP) {
      return fail(`invalid typ: expected ${SIWD_JWS_TYP}, got ${decoded.header.typ}`);
    }

    const kid = decoded.header.kid;
    if (typeof kid !== 'string') return fail('kid must be a DID URL');
    const hashIdx = kid.indexOf('#');
    if (hashIdx < 0) return fail('kid must be a DID URL');
    const did = kid.substring(0, hashIdx);
    const keyId = kid.substring(hashIdx + 1);

    // Parse the original payload octets, not decodeJwsUnsafe's lossy JSON view:
    // duplicate members and non-canonical spellings must remain observable.
    const payloadSegment = jws.split('.')[1];
    if (payloadSegment === undefined) return fail('failed to decode JWS payload');
    const payload = parseSiwdChallenge(base64urlDecode(payloadSegment));

    // challenge binding — if the challenge names a DID it must match the signer
    if (payload.did !== undefined && payload.did !== did) {
      return fail('challenge did does not match signer');
    }
    if (expect.did !== undefined && expect.did !== did) {
      return fail('signer did does not match expected did');
    }

    // resolve the identity to its CURRENT state — and fail CLOSED when the tip
    // could not be verified. Auth is the one place trust never silently
    // degrades: "current authKeys" from a stale cache would let a rotated-out
    // key keep verifying. `allowStale: true` is the explicit opt-out.
    const resolved = await client.identity(did);
    const unverifiable = resolved.trust.unverifiable ?? [];
    if (!expect.allowStale && (unverifiable.includes('tip') || resolved.provenance.fromCache)) {
      return fail(
        'identity resolution is stale (tip unverified) — refusing to authenticate against ' +
          'a cached identity state; pass allowStale: true to accept the risk',
      );
    }
    const state = resolved.value;
    if (state.isDeleted) return fail('identity is deleted');

    // key MUST be a current authKey (rotated-out keys MUST NOT verify)
    const authKey = state.authKeys.find((k) => k.id === keyId);
    if (!authKey) return fail('signing key is not a current authentication key');

    // verify the signature under the DFOS profile
    const publicKey = decodeMultikey(authKey.publicKeyMultibase).keyBytes;
    try {
      verifyJws({ token: jws, publicKey });
    } catch (err) {
      return fail(err instanceof Error ? err.message : 'invalid signature');
    }

    // the signed payload must match what the verifier expects — domain, and
    // (when pinned) the exact timestamp it minted
    if (payload.domain !== expect.domain) return fail('domain mismatch');
    if (expect.timestamp !== undefined && payload.timestamp !== expect.timestamp) {
      return fail('timestamp does not match expected challenge timestamp');
    }

    // timestamp window — bounded in BOTH directions: a stale challenge is
    // replayable history, a future-dated one would outlive every maxAge window
    const maxAge = expect.maxAgeSeconds ?? 300;
    const nowMs = expect.now ? expect.now() : Date.now();
    const issuedMs = Date.parse(payload.timestamp);
    if (Number.isNaN(issuedMs)) return fail('invalid timestamp');
    if (nowMs - issuedMs > maxAge * 1000) return fail('challenge expired');
    if (issuedMs - nowMs > MAX_CLOCK_SKEW_SECONDS * 1000) {
      return fail('challenge timestamp is in the future');
    }

    // NONCE LAST, and the position is the semantics: `consumeNonce` SPENDS
    // verifier state, so nothing invalid may reach it — a forged signature, a
    // rotated-out key, a mismatched domain, an expired challenge must never
    // burn a nonce the real user is still holding, and the consume is then the
    // final gate before the caller grants anything. The string form rides along
    // in the same place so both disciplines fail identically.
    if (expect.consumeNonce !== undefined) {
      if (!(await expect.consumeNonce(payload.nonce))) {
        return fail('nonce already used or not recognized');
      }
    } else if (payload.nonce !== expect.nonce) {
      return fail('nonce mismatch');
    }

    const session: SiwdSession = {
      did,
      domain: payload.domain,
      nonce: payload.nonce,
      timestamp: payload.timestamp,
      kid,
      ...(payload.statement !== undefined ? { statement: payload.statement } : {}),
    };
    return {
      ok: true,
      value: session,
      // surface the resolution's honest gaps either way (populated only on the
      // allowStale path — the default path fails closed above)
      ...(unverifiable.length > 0 ? { unverifiable } : {}),
    };
  } catch (err) {
    return fail(err instanceof Error ? err.message : 'siwd verification failed');
  }
};
