/*

  @metalabel/dfos-client/siwd

  Sign In With DFOS — the three load-bearing pieces of the challenge/response,
  and nothing more. The unlock is NOT a fat verifier; it is `siwdSigningInput`,
  the PURE byte contract both halves share. A browser wallet signs those exact
  bytes; a verifier re-derives them. Without it the challenge→JWS encoding lives
  nowhere and the two sides drift silently. See specs/SIWD.md.

  Verification follows SIWD.md §Third-Party Verification: the signing key MUST be
  a CURRENT `authKeys` entry of a non-deleted identity — rotated-out keys and
  deleted identities MUST NOT verify.

*/

import {
  buildSignRequest,
  decodeMultikey,
  SignRequestVerifyError,
  verifySignRequest,
  type Signer,
  type VerifiedIdentity,
  type VerifiedSignRequest,
} from '@metalabel/dfos-protocol/chain';
import {
  assertJwsProfile,
  base64urlDecode,
  base64urlEncode,
  decodeJwsUnsafe,
  generateIdNoPrefix,
  verifyJws,
} from '@metalabel/dfos-protocol/crypto';
import type { Client, VerifyResult } from './types';

// -----------------------------------------------------------------------------
// challenge
// -----------------------------------------------------------------------------

/**
 * The normative JWS header `typ` for a signed SIWD challenge (SIWD.md). Signers
 * MUST set it; `verifySiwd` rejects anything else — it is also what lets typ-
 * routing dispatchers tell a SIWD proof apart from credentials and chain ops.
 */
export const SIWD_JWS_TYP = 'did:dfos:siwd';

/** Allowed forward clock skew when validating challenge timestamps (seconds). */
const MAX_CLOCK_SKEW_SECONDS = 60;

export interface SiwdChallenge {
  /** Origin domain of the requesting application. */
  domain: string;
  /** Unique replay-prevention value generated by the third party. */
  nonce: string;
  /** ISO 8601 timestamp of challenge creation. */
  timestamp: string;
  /** Human-readable description shown on the consent screen. */
  statement?: string;
  /** Binds the challenge to a specific DID. */
  did?: string;
}

export interface SiwdSession {
  did: string;
  domain: string;
  nonce: string;
  timestamp: string;
  statement?: string;
  /** The DID URL of the key that signed the challenge. */
  kid: string;
}

const SIWD_CHALLENGE_FIELDS = new Set(['domain', 'nonce', 'timestamp', 'statement', 'did']);
const WHOLE_SECOND_TIMESTAMP = /^\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}\.000Z$/;
const LONE_SURROGATE = /[\uD800-\uDBFF](?![\uDC00-\uDFFF])|(?<![\uD800-\uDBFF])[\uDC00-\uDFFF]/;
const MAX_SIGN_REQUEST_WINDOW_SECONDS = 604_800;

const validateSiwdChallenge = (value: unknown): SiwdChallenge => {
  if (typeof value !== 'object' || value === null || Array.isArray(value)) {
    throw new Error('invalid SIWD challenge: expected a JSON object');
  }

  const raw = value as Record<string, unknown>;
  for (const field of Object.keys(raw)) {
    if (!SIWD_CHALLENGE_FIELDS.has(field)) {
      throw new Error(`invalid SIWD challenge: unknown member ${field}`);
    }
  }

  for (const field of ['domain', 'nonce', 'timestamp'] as const) {
    if (typeof raw[field] !== 'string' || raw[field].length === 0) {
      throw new Error(`invalid SIWD challenge: ${field} must be a non-empty string`);
    }
  }
  for (const field of ['statement', 'did'] as const) {
    if (raw[field] !== undefined && typeof raw[field] !== 'string') {
      throw new Error(`invalid SIWD challenge: ${field} must be a string when present`);
    }
  }

  const strings = [raw['domain'], raw['nonce'], raw['timestamp'], raw['statement'], raw['did']];
  if (strings.some((field) => typeof field === 'string' && LONE_SURROGATE.test(field))) {
    throw new Error('invalid SIWD challenge: string members must be well-formed Unicode');
  }

  const timestamp = raw['timestamp'] as string;
  const timestampMs = Date.parse(timestamp);
  if (
    !WHOLE_SECOND_TIMESTAMP.test(timestamp) ||
    Number.isNaN(timestampMs) ||
    new Date(timestampMs).toISOString() !== timestamp
  ) {
    throw new Error('invalid SIWD challenge: timestamp must be ISO-8601 UTC whole-second .000Z');
  }

  return {
    domain: raw['domain'] as string,
    nonce: raw['nonce'] as string,
    timestamp,
    ...(raw['statement'] !== undefined ? { statement: raw['statement'] as string } : {}),
    ...(raw['did'] !== undefined ? { did: raw['did'] as string } : {}),
  };
};

/**
 * The byte contract. Serializes a challenge to the canonical bytes that ARE the
 * JWS payload and the base64url query-param body — a fixed key order
 * (domain, nonce, timestamp, statement?, did?) so both halves agree exactly.
 * PURE and clientless: import it in an edge minter and in a browser wallet alike.
 */
export const siwdSigningInput = (challenge: SiwdChallenge): Uint8Array => {
  const parsed = validateSiwdChallenge(challenge);
  const canonical: Record<string, unknown> = {
    domain: parsed.domain,
    nonce: parsed.nonce,
    timestamp: parsed.timestamp,
  };
  if (parsed.statement !== undefined) canonical['statement'] = parsed.statement;
  if (parsed.did !== undefined) canonical['did'] = parsed.did;
  return new TextEncoder().encode(JSON.stringify(canonical));
};

/**
 * Parse exact SIWD challenge octets under the signer-side WYSIWYS contract.
 * The input must be UTF-8 JSON, satisfy the closed challenge schema, and equal
 * the canonical serialization byte for byte.
 */
export const parseSiwdChallenge = (octets: Uint8Array): SiwdChallenge => {
  let source: string;
  try {
    source = new TextDecoder('utf-8', { fatal: true }).decode(octets);
  } catch {
    throw new Error('invalid SIWD challenge: payload is not valid UTF-8 JSON');
  }
  if (source.startsWith('\uFEFF')) {
    throw new Error('invalid SIWD challenge: payload must not carry a UTF-8 BOM');
  }

  let raw: unknown;
  try {
    raw = JSON.parse(source);
  } catch {
    throw new Error('invalid SIWD challenge: payload is not valid JSON');
  }
  const challenge = validateSiwdChallenge(raw);
  const canonical = siwdSigningInput(challenge);
  if (
    canonical.length !== octets.length ||
    !canonical.every((byte, index) => byte === octets[index])
  ) {
    throw new Error('invalid SIWD challenge: payload bytes are not canonical');
  }
  return challenge;
};

export interface CreateChallengeInput {
  domain: string;
  statement?: string;
  did?: string;
  /** Provide a nonce, or one is generated. */
  nonce?: string;
  /** Provide a timestamp, or `now` is used. */
  timestamp?: string;
  /** Clock injection (unix ms) for the timestamp. Default `Date.now()`. */
  now?: () => number;
}

/**
 * Mint a challenge, clientless and edge-safe. Returns the challenge object, the
 * base64url `encoded` form for the `/authorize?challenge=` query param, and the
 * nonce for server-side replay storage. `encoded` is exactly
 * base64url(siwdSigningInput(challenge)) — the same bytes the wallet signs.
 */
export const createSiwdChallenge = (
  input: CreateChallengeInput,
): { challenge: SiwdChallenge; encoded: string; nonce: string } => {
  const nonce = input.nonce ?? generateIdNoPrefix();
  const timestampValue =
    input.timestamp ?? new Date(input.now ? input.now() : Date.now()).toISOString();
  const timestampMs = Date.parse(timestampValue);
  if (Number.isNaN(timestampMs)) {
    throw new Error(`invalid SIWD challenge: unparseable timestamp: ${timestampValue}`);
  }
  const timestamp = new Date(Math.floor(timestampMs / 1000) * 1000).toISOString();
  const challenge: SiwdChallenge = {
    domain: input.domain,
    nonce,
    timestamp,
    ...(input.statement !== undefined ? { statement: input.statement } : {}),
    ...(input.did !== undefined ? { did: input.did } : {}),
  };
  const encoded = base64urlEncode(siwdSigningInput(challenge));
  return { challenge, encoded, nonce };
};

/** Decode a base64url `challenge` query-param body back into a challenge object. */
export const decodeSiwdChallenge = (encoded: string): SiwdChallenge =>
  parseSiwdChallenge(base64urlDecode(encoded));

// -----------------------------------------------------------------------------
// profile A login kit
// -----------------------------------------------------------------------------

/**
 * Hostnames that make a redirect a LOOPBACK redirect — a CLI or a desktop app
 * listening on a local port. Exact matches only: `127.0.0.2` and
 * `localhost.evil.example` are NOT loopback, and quietly treating them as such
 * would strip a client DID from a request that was entitled to assert one.
 */
const SIWD_LOOPBACK_HOSTS = new Set(['localhost', '127.0.0.1', '::1']);

/**
 * `URL.hostname` brackets an IPv6 literal because the brackets are URL grammar,
 * not part of the name — so `[::1]` and `::1` are the same host.
 */
const bareHostname = (url: URL): string => {
  const host = url.hostname.toLowerCase();
  return host.startsWith('[') && host.endsWith(']') ? host.slice(1, -1) : host;
};

const parseUrlOrThrow = (value: string, field: string): URL => {
  try {
    return new URL(value);
  } catch {
    throw new Error(`invalid SIWD login request: ${field} must be an absolute URL`);
  }
};

export interface SiwdLoginRequestInput {
  /** The host's authorize endpoint, e.g. `https://app.example.com/authorize`. */
  authorizeUrl: string;
  /** The RP's own domain — bound into the signed challenge as a bare hostname. */
  domain: string;
  /** Exact redirect target; must match the RP's registered or served allowlist. */
  redirectUri: string;
  /** Requested scope. `identity` is the only scope implemented today. */
  scope: string;
  /** Consent-screen prose. A host MAY decline to render it; see specs/SIWD.md. */
  statement?: string;
  /**
   * Bind the challenge to ONE identity — "sign in as this DID, or not at all".
   * Threaded into the signed bytes AND into `expect`, because binding a
   * challenge without verifying the binding proves nothing: a host that ignored
   * it would return a signature from whoever was logged in, and an RP checking
   * only the signature would accept it.
   */
  did?: string;
  /** The RP's own DID. Omitted from the URL automatically for loopback redirects. */
  clientDid?: string;
  /** Supply a nonce minted elsewhere (e.g. by your backend); default: minted here. */
  nonce?: string;
}

export interface SiwdLoginRequest {
  /** Navigate the browser here, or hand it to the user. */
  url: string;
  /**
   * THE THING TO PERSIST ACROSS THE REDIRECT. One JSON-serializable object that
   * satisfies `SiwdExpectations`, so the whole round trip is: store this before
   * navigating, rehydrate it when the callback lands, and hand it straight to
   * `verifySiwd(client, jws, saved)`. Nothing else has to survive the hop, and
   * nothing has to be threaded to both ends by hand — which is the point, since
   * a `domain` or `did` that drifts between mint and verify is a check that
   * silently stops checking.
   *
   * SINGLE USE: consume the nonce on the way back, pass or fail.
   *
   * WHOEVER VERIFIES MUST HAVE MINTED. A verifier that accepts an expectation
   * supplied by the party presenting the JWS is comparing a value against
   * itself and has verified nothing — the replay guard binds only when the
   * expectation comes from the verifier's own prior state (this object, held
   * server-side or in the session that began the sign-in) or from an
   * independent validation of it.
   */
  expect: Pick<SiwdExpectations, 'domain' | 'nonce' | 'did'>;
  /** base64url canonical challenge bytes, exactly as embedded in `url`. */
  challenge: string;
  /** ISO whole-second mint timestamp, exactly as embedded in the signed bytes. */
  timestamp: string;
}

/**
 * Mint a challenge and build the `/authorize` URL to send the browser to — the
 * OUTBOUND half of profile A. `readSiwdCallback` is the inbound half, and
 * `verifySiwd` is what both compose around: mint → redirect, read → verify.
 *
 * The rule this function exists to own is the LOOPBACK OMISSION. Nothing can
 * prove a client DID for an app on a local port — there is no domain serving a
 * well-known and no registration to check — so a host REFUSES a `client_did`
 * on a loopback redirect rather than displaying an identity it cannot stand
 * behind. A CLI that passed its own DID would have the whole request rejected,
 * not downgraded, so the param is dropped here instead of being forwarded into
 * a guaranteed refusal.
 *
 * It also owns the WIRE PARAM NAMES (`challenge`, `redirect_uri`, `scope`,
 * `client_did`) as their single source in this package. They are snake_case on
 * the wire and camelCase everywhere else, which is exactly the kind of seam
 * every hand-rolled RP re-implements and eventually gets wrong.
 *
 * PURE: no DOM, no storage, no navigation, no fetch — identical in a browser
 * and in Node. Throws on an unparseable `authorizeUrl` or `redirectUri`,
 * because those are mistakes in the RP's own configuration rather than runtime
 * conditions a result type would help a caller recover from.
 */
export const createSiwdLoginRequest = (input: SiwdLoginRequestInput): SiwdLoginRequest => {
  const authorizeUrl = parseUrlOrThrow(input.authorizeUrl, 'authorizeUrl');
  const redirect = parseUrlOrThrow(input.redirectUri, 'redirectUri');

  const { challenge, encoded, nonce } = createSiwdChallenge({
    domain: input.domain,
    ...(input.statement !== undefined ? { statement: input.statement } : {}),
    ...(input.did !== undefined ? { did: input.did } : {}),
    ...(input.nonce !== undefined ? { nonce: input.nonce } : {}),
  });

  // Built on a COPY of the parsed authorize URL so any query the host endpoint
  // already carries survives instead of being clobbered by concatenation.
  const url = new URL(authorizeUrl);
  url.searchParams.set('challenge', encoded);
  url.searchParams.set('redirect_uri', input.redirectUri);
  url.searchParams.set('scope', input.scope);
  if (input.clientDid !== undefined && !SIWD_LOOPBACK_HOSTS.has(bareHostname(redirect))) {
    url.searchParams.set('client_did', input.clientDid);
  }

  return {
    url: url.toString(),
    expect: {
      domain: input.domain,
      nonce,
      ...(input.did !== undefined ? { did: input.did } : {}),
    },
    challenge: encoded,
    timestamp: challenge.timestamp,
  };
};

/**
 * What came back on the redirect. `none` means this was a plain page load, not
 * a callback at all — the common case on an RP's own landing page.
 */
export type SiwdCallbackResult =
  | { kind: 'success'; jws: string; did: string }
  | { kind: 'denied'; error: string }
  | { kind: 'none' };

/** An empty value carries no more information than an absent one. */
const callbackParam = (params: URLSearchParams, key: string): string | undefined => {
  const value = params.get(key);
  return value === null || value === '' ? undefined : value;
};

/**
 * Accept the three things a caller actually has in hand: a full URL, a `URL`,
 * or a bare query string — `location.search` is what a browser RP reaches for,
 * and it is `''` on a plain page load, which must read as "no callback" rather
 * than blow up on the most common path through the function.
 */
const callbackParams = (url: string | URL): URLSearchParams => {
  if (typeof url !== 'string') return url.searchParams;
  if (url === '' || url.startsWith('?')) return new URLSearchParams(url);
  return parseUrlOrThrow(url, 'url').searchParams;
};

/**
 * Read a profile-A callback — the INBOUND half of the pair. Pure parse: it
 * decides only what kind of return this is, and hands `jws` to the caller for
 * `verifySiwd`. NOTHING here is trusted; the `did` param is unauthenticated
 * courier convenience, and the DID a caller should act on is the one
 * `verifySiwd` returns from the signature.
 *
 * Takes an absolute URL string, a `URL`, or a bare `?…` query string (so
 * `readSiwdCallback(location.search)` works, including when it is empty).
 *
 * SCRUB THE URL YOURSELF, IMMEDIATELY. A signed JWS is sitting in the query
 * string, which means it is in the address bar, in `history`, in the referrer
 * of anything the page loads next, and in any analytics that samples the
 * location. This function cannot do the scrubbing for you — `history` is
 * environment-owned and this package stays free of the DOM — so a browser RP
 * should follow the read with a `history.replaceState` back to the bare path.
 *
 * A HALF-CALLBACK IS A FAILURE, NOT A NON-EVENT: `jws` without `did` (or the
 * reverse) resolves to `denied` carrying a synthetic reason rather than `none`.
 * Silently treating it as a plain page load would strand the user on a
 * sign-in button with no explanation of why the last attempt vanished.
 */
export const readSiwdCallback = (url: string | URL): SiwdCallbackResult => {
  const params = callbackParams(url);
  const jws = callbackParam(params, 'jws');
  const did = callbackParam(params, 'did');
  const error = callbackParam(params, 'error');

  if (jws !== undefined && did !== undefined) return { kind: 'success', jws, did };
  if (error !== undefined) return { kind: 'denied', error };
  if (jws !== undefined) return { kind: 'denied', error: 'malformed SIWD callback: missing did' };
  if (did !== undefined) return { kind: 'denied', error: 'malformed SIWD callback: missing jws' };
  return { kind: 'none' };
};

// -----------------------------------------------------------------------------
// sign-request profile B
// -----------------------------------------------------------------------------

export interface BuildSiwdSignRequestInput {
  /** Requester DID that signs the courier envelope. */
  did: string;
  /** DID being asked to sign the SIWD artifact. */
  subject: string;
  challenge: SiwdChallenge;
  /** Explicit composer policy; no implicit SIWD mailbox lifetime exists. */
  acceptanceWindowSeconds: number;
  expiresAt: string;
  createdAt?: string;
  signer: Signer;
  keyId: string;
}

export interface ValidateSiwdSignRequestOptions {
  signerDid: string;
  /** Must be the composer's stated acceptance policy for this request. */
  acceptanceWindowSeconds: number;
  resolveIdentity: (did: string) => Promise<VerifiedIdentity | undefined>;
  /** Unix milliseconds; defaults to Date.now(). */
  now?: number;
}

export interface ValidatedSiwdSignRequest extends VerifiedSignRequest {
  /** Strictly parsed canonical challenge used by the signer for rendering. */
  challenge: SiwdChallenge;
}

const assertSiwdAcceptanceWindow = (seconds: number): void => {
  if (!Number.isSafeInteger(seconds) || seconds <= 0) {
    throw new Error('SIWD acceptanceWindowSeconds must be a positive integer');
  }
  if (seconds > MAX_SIGN_REQUEST_WINDOW_SECONDS) {
    throw new Error('SIWD acceptanceWindowSeconds exceeds the sign-request 604800-second ceiling');
  }
};

const assertSiwdOneClock = (
  challengeTimestamp: string,
  expiresAt: string,
  acceptanceWindowSeconds: number,
): void => {
  assertSiwdAcceptanceWindow(acceptanceWindowSeconds);
  const challengeMs = Date.parse(challengeTimestamp);
  const expiresMs = Date.parse(expiresAt);
  if (Number.isNaN(expiresMs)) {
    throw new Error(`invalid SIWD sign request: unparseable expiresAt: ${expiresAt}`);
  }
  const normalizedExpiresMs = Math.floor(expiresMs / 1000) * 1000;
  if (normalizedExpiresMs > challengeMs + acceptanceWindowSeconds * 1000) {
    throw new Error('SIWD sign request expiresAt exceeds the challenge acceptance window');
  }
};

/** Compose SIWD profile B using the generic sign-request envelope. */
export const buildSiwdSignRequest = async (
  input: BuildSiwdSignRequestInput,
): Promise<{ jwsToken: string; requestCID: string }> => {
  const challenge = validateSiwdChallenge(input.challenge);
  if (challenge.did !== undefined && challenge.did !== input.subject) {
    throw new Error('SIWD challenge did does not match sign request subject');
  }
  assertSiwdOneClock(challenge.timestamp, input.expiresAt, input.acceptanceWindowSeconds);
  return buildSignRequest({
    did: input.did,
    subject: input.subject,
    payloadTyp: SIWD_JWS_TYP,
    payload: siwdSigningInput(challenge),
    expiresAt: input.expiresAt,
    ...(input.createdAt !== undefined ? { createdAt: input.createdAt } : {}),
    signer: input.signer,
    keyId: input.keyId,
  });
};

/** Verify and strictly parse a SIWD profile-B request before rendering/signing. */
export const validateSiwdSignRequest = async (
  jwsToken: string,
  options: ValidateSiwdSignRequestOptions,
): Promise<ValidatedSiwdSignRequest> => {
  assertSiwdAcceptanceWindow(options.acceptanceWindowSeconds);
  const request = await verifySignRequest(jwsToken, {
    resolveIdentity: options.resolveIdentity,
    ...(options.now !== undefined ? { now: options.now } : {}),
  });
  // Every post-envelope family gate is a definitive "invalid" verdict — wrap in
  // the sign-request error taxonomy so consumers branch on `reason`, matching
  // the Go twin (ErrSignRequestInvalid), never on message text.
  const invalid = (message: string) => new SignRequestVerifyError('invalid', message);
  if (request.subject !== options.signerDid) {
    throw invalid('SIWD sign request subject does not match signer DID');
  }
  if (request.payloadTyp !== SIWD_JWS_TYP) {
    throw invalid(`invalid SIWD sign request payloadTyp: ${request.payloadTyp}`);
  }
  let challenge: SiwdChallenge;
  try {
    challenge = parseSiwdChallenge(request.payloadBytes);
    assertSiwdOneClock(challenge.timestamp, request.expiresAt, options.acceptanceWindowSeconds);
  } catch (err) {
    throw invalid(err instanceof Error ? err.message : 'invalid SIWD sign request payload');
  }
  if (challenge.did !== undefined && challenge.did !== options.signerDid) {
    throw invalid('SIWD challenge did does not match signer DID');
  }
  return { ...request, challenge };
};

// -----------------------------------------------------------------------------
// verify
// -----------------------------------------------------------------------------

export interface SiwdExpectations {
  /** The verifier's own origin — MUST match the challenge domain. */
  domain: string;
  /** The nonce this verifier issued for the session. */
  nonce: string;
  /** If set, the challenge (and identity) MUST bind to this DID. */
  did?: string;
  /** If set, the signed challenge's timestamp MUST equal this exact value. */
  timestamp?: string;
  /** Reject challenges older than this many seconds. Default 300 (5 min). */
  maxAgeSeconds?: number;
  /**
   * Accept an identity resolution whose tip could not be verified (cache-only
   * or empty-delta-against-cache). Default FALSE: authentication never silently
   * degrades — a rotated-out key must not verify against a stale cached state.
   */
  allowStale?: boolean;
  /** Clock injection (unix ms). Default `Date.now()`. */
  now?: () => number;
}

const fail = (error: string): VerifyResult<SiwdSession> => ({ ok: false, error });

/**
 * Verify a SIWD challenge JWS. No-throw. The signature is checked under the DFOS
 * profile (via the protocol's `verifyJws`), against a CURRENT `authKeys` entry
 * of a non-deleted identity resolved through the client. Nonce, timestamp
 * window, and domain are validated against `expect`.
 */
export const verifySiwd = async (
  client: Client,
  jws: string,
  expect: SiwdExpectations,
): Promise<VerifyResult<SiwdSession>> => {
  try {
    const decoded = decodeJwsUnsafe(jws);
    if (!decoded) return fail('failed to decode JWS');

    const rawHeader = decoded.header as unknown;
    if (typeof rawHeader !== 'object' || rawHeader === null || Array.isArray(rawHeader)) {
      return fail('SIWD protected header must be an object');
    }
    assertJwsProfile(rawHeader as Record<string, unknown>, (message) => new Error(message));

    // typ gate — normative per SIWD.md; also what client.verify() routes on
    if (decoded.header.typ !== SIWD_JWS_TYP) {
      return fail(`invalid typ: expected ${SIWD_JWS_TYP}, got ${decoded.header.typ}`);
    }

    const kid = decoded.header.kid;
    if (typeof kid !== 'string') return fail('kid must be a DID URL');
    const hashIdx = kid.indexOf('#');
    if (hashIdx < 0) return fail('kid must be a DID URL');
    const did = kid.substring(0, hashIdx);
    const keyId = kid.substring(hashIdx + 1);

    // Parse the original payload octets, not decodeJwsUnsafe's lossy JSON view:
    // duplicate members and non-canonical spellings must remain observable.
    const payloadSegment = jws.split('.')[1];
    if (payloadSegment === undefined) return fail('failed to decode JWS payload');
    const payload = parseSiwdChallenge(base64urlDecode(payloadSegment));

    // challenge binding — if the challenge names a DID it must match the signer
    if (payload.did !== undefined && payload.did !== did) {
      return fail('challenge did does not match signer');
    }
    if (expect.did !== undefined && expect.did !== did) {
      return fail('signer did does not match expected did');
    }

    // resolve the identity to its CURRENT state — and fail CLOSED when the tip
    // could not be verified. Auth is the one place trust never silently
    // degrades: "current authKeys" from a stale cache would let a rotated-out
    // key keep verifying. `allowStale: true` is the explicit opt-out.
    const resolved = await client.identity(did);
    const unverifiable = resolved.trust.unverifiable ?? [];
    if (!expect.allowStale && (unverifiable.includes('tip') || resolved.provenance.fromCache)) {
      return fail(
        'identity resolution is stale (tip unverified) — refusing to authenticate against ' +
          'a cached identity state; pass allowStale: true to accept the risk',
      );
    }
    const state = resolved.value;
    if (state.isDeleted) return fail('identity is deleted');

    // key MUST be a current authKey (rotated-out keys MUST NOT verify)
    const authKey = state.authKeys.find((k) => k.id === keyId);
    if (!authKey) return fail('signing key is not a current authentication key');

    // verify the signature under the DFOS profile
    const publicKey = decodeMultikey(authKey.publicKeyMultibase).keyBytes;
    try {
      verifyJws({ token: jws, publicKey });
    } catch (err) {
      return fail(err instanceof Error ? err.message : 'invalid signature');
    }

    // the signed payload must match what the verifier expects — nonce, domain,
    // and (when pinned) the exact timestamp it minted
    if (payload.nonce !== expect.nonce) return fail('nonce mismatch');
    if (payload.domain !== expect.domain) return fail('domain mismatch');
    if (expect.timestamp !== undefined && payload.timestamp !== expect.timestamp) {
      return fail('timestamp does not match expected challenge timestamp');
    }

    // timestamp window — bounded in BOTH directions: a stale challenge is
    // replayable history, a future-dated one would outlive every maxAge window
    const maxAge = expect.maxAgeSeconds ?? 300;
    const nowMs = expect.now ? expect.now() : Date.now();
    const issuedMs = Date.parse(payload.timestamp);
    if (Number.isNaN(issuedMs)) return fail('invalid timestamp');
    if (nowMs - issuedMs > maxAge * 1000) return fail('challenge expired');
    if (issuedMs - nowMs > MAX_CLOCK_SKEW_SECONDS * 1000) {
      return fail('challenge timestamp is in the future');
    }

    const session: SiwdSession = {
      did,
      domain: payload.domain,
      nonce: payload.nonce,
      timestamp: payload.timestamp,
      kid,
      ...(payload.statement !== undefined ? { statement: payload.statement } : {}),
    };
    return {
      ok: true,
      value: session,
      // surface the resolution's honest gaps either way (populated only on the
      // allowStale path — the default path fails closed above)
      ...(unverifiable.length > 0 ? { unverifiable } : {}),
    };
  } catch (err) {
    return fail(err instanceof Error ? err.message : 'siwd verification failed');
  }
};
